### ISSUE TITLE
 No module named 'sanifix4'

### ISSUE THREAD

**Issue by Rong0802** [tbereau/auto_martini#17]
hello,
someone can help me please.
I am still new in the use of python
I was unable to find the sanifix4 module when I installed auto-martini. Then I use pip install sanifix4 to install sanifix4, the error is as follows：
ERROR: Could not find a version that satisfies the requirement sanifix4 (from versions: none)
ERROR: No matching distribution found for sanifix4

How can I solve this problem?

**Comment by kkanekal** [comment]
Hi,

Thanks for bringing this to my attention. I forgot to add the sanifix4.py file when I updated the master branch. The problem should be fixed now. You can either just update your existing branch by typing "git pull" in the auto_martini folder, or you can just checkout or re-download the code again.

-Kiran

**Comment by Rong0802** [comment]
Thank you for your replay
I re-download the code. But the new problem has appeared again. When I run auto_martini, I get the following error:

(my-rdkit-env) PS D:\work_software\auto-martini\auto_martini-master> python .\auto_martini
Traceback (most recent call last):
  File ".\auto_martini", line 38, in <module>
    from sanifix4 import AdjustAromaticNs
  File "D:\work_software\auto-martini\auto_martini-master\sanifix4.py", line 277

How can I solve this problem?

**Comment by Rong0802** [comment]
> Thank you for your replay
> I re-download the code. But the new problem has appeared again. When I run auto_martini, I get the following error:
> 
> (my-rdkit-env) PS D:\work_software\auto-martini\auto_martini-master> python .\auto_martini
> Traceback (most recent call last):
> File ".\auto_martini", line 38, in
> from sanifix4 import AdjustAromaticNs
> File "D:\work_software\auto-martini\auto_martini-master\sanifix4.py", line 277
print '#---------------------'
                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('#---------------------')?
> 
> How can I solve this problem?

**Comment by kkanekal** [comment]
Hi,

I suspect that this error is due to the fact that you are using Python 3, whereas the code is meant to run on Python 2.7.X.  

-Kiran

**Comment by Rong0802** [comment]
Hello, the sanifix problem has been solved. When I tried "auto-martini --smi "N1=C(N)NN=C1N" --mol GUA", the program reported the following error:

(my-rdkit-env) PS D:\work_software\auto-martini\auto_martini-master> python .\auto_martini --smi "N1=C(N)NN=C1N" --mol G
UA
Traceback (most recent call last):
  File ".\auto_martini", line 1389, in <module>
    cg_molecule(mol, args.molname, args.aa, args.cg, args.forcepred)
  File ".\auto_martini", line 1270, in cg_molecule
    ring_atoms_flat)
  File ".\auto_martini", line 498, in find_bead_pos
    acceptable_trial = check_beads(list_heavy_atoms, heavyatom_coords, trial_comb, ring_atoms, list_bonds)
  File ".\auto_martini", line 408, in check_beads
    for bi in xrange(len(trial_comb)):
NameError: name 'xrange' is not defined

How can I solve this problem?

**Comment by kkanekal** [comment]
Hi,

Again, this is a Python 3 issue. As far as I can understand the xrange function was renamed to range in Python 3. If you intend to convert the code to be compatible with Python 3 and not run it in Python 2.7.x, I highly recommend you google the errors you are getting before commenting here, as I am still unfamiliar with the specific differences between the two versions of Python and will only be of limited help.

-Kiran

**Comment by Rong0802** [comment]
Hi
I have successfully installed auto-martini, but there is a new problem when I run the program.
usage: auto_martini [-h] (--sdf SDF | --smi SMI) --mol MOLNAME [--aa AA]
                    [--cg CG] [-v] [--fpred]
auto_martini: error: argument --mol is required
(my-rdkit-env) sun@sun-QiTianM620-N000:~/桌面/auto-martini/auto_martini-master$ python auto_martini --sdf peg400.sdf --mol PEG
WARNING:__main__:Error with BeautifulSoup constructor
How can I solve this problem?

**Comment by kkanekal** [comment]
Hi,

Try running the following python code:

`from bs4 import BeautifulSoup
import lxml
import requests
session = requests.session()
req = session.get('http://vcclab.org/web/alogps/calc?SMILES=CCCC')
doc = BeautifulSoup(req.content, "lxml")
soup = doc.prettify()
print soup`

you should get this output:

`<html>
 <body>
  mol_N logP logS SMILES
  <br/>
  mol_1 2.81 -1.91 CCCC
  <br/>
 </body>
</html>`

Is this the case?
