### ISSUE TITLE
Problem in 'smi2alogps %s" % smiFrag'

### ISSUE THREAD

**Issue by Snehadixit1994** [tbereau/auto_martini#7]
Hi,
I wish to use auto-martini for getting CG file for my drug.
I tried to use the example given here.
However, I am getting following error- 

 python auto_martini --smi "N1=C(N)N python auto_martini --smi "N1=C(N)NN=C1N" --mol GUA
Traceback (most recent call last):
  File "auto_martini", line 1204, in <module>
    ringAtomsFlat, True)
  File "auto_martini", line 835, in printAtoms
    raise Exception("Problem in smi2alogps %s" % smiFrag)
Exception: Problem in smi2alogps Nc1ncnn1

Also, when I was trying to run this script for my molecule, I received this error -
Error. Exhaustive enumeration can't handle large molecules.
Number of heavy atoms: 41

Please help me in this regard.

**Comment by tbereau** [comment]
Could you check whether your BeautifulSoup package is working correctly? Try adding the following statement at line 677:
```
print soup
```
(It should right beneath `soup = doc.prettify()`

As for the enumeration issue, auto_martini can't handle large molecules at the moment. That's due to the current exhaustive enumeration of bead mappings--preventing it from working with large molecules. One alternative you have is to break up your molecules into fragments, coarse-grain those, and then connect them yourself.

Best,
Tristan

**Comment by tbereau** [comment]
Any update? Something else that came up is the requirement to have the 'lxml' package. Could you check whether the command
```
import lxml
```
returns without an error? If not, try installing it (using pip or equivalent).

Best,
Tristan

**Comment by Snehadixit1994** [comment]
Respected sir,

I added 'print soup' at line 677 below soup = doc.prettify() as you had
suggested.
Also, lxml was imported.
now I am receiving following error


python auto_martini --sdf gua.sdf --mol gua --verbose
; ring atoms: [[0, 2, 6, 1, 5]]
; Heavy atoms: N N N N N C C
; [0] -43.5137590647
; [1] -48.8876118299
; [2] -43.5139391855
; [5] -45.7019823874
; [6] -45.7018655559
; [0, 1] -87.3909378371
; [0, 6] -87.0065915631
; [1, 2] -87.3911080548
; [2, 5] -87.0068963568
; [5, 6] -89.1948049826
; CG bead: 5
; CG bead: 6
;      with energy: -89.1948049826
; Max. number of attempts: 5
; Atom partitioning: {0: 0, 1: 0, 2: 1, 3: 0, 4: 1, 5: 0, 6: 1}
Traceback (most recent call last):
  File "auto_martini", line 1205, in <module>
    ringAtomsFlat, True)
  File "auto_martini", line 827, in printAtoms
    molFrag = genMoleculeSMI(smiFrag)
  File "auto_martini", line 90, in genMoleculeSMI
    mol = Chem.MolFromSmiles(args.smi)
TypeError: No registered converter was able to produce a C++ rvalue of type
std::basic_string<wchar_t, std::char_traits<wchar_t>,
std::allocator<wchar_t> > from this Python object of type NoneType


Sincerely,
Sneha

**Comment by tbereau** [comment]
Could you try with the `refactor` branch? Simply type 
```
git checkout refactor
```
and then running the code is slightly different:
```
python auto_martini.py --sdf gua.sdf --mol gua --verbose
```
Also, I typically run the code with smiles string rather than sdf files. I'd recommend you first convert your sdf file to a smiles string (e.g., using OpenBabel) and then run the code from the smiles string (as you had it in your initial post).

Best,
Tristan

**Comment by Snehadixit1994** [comment]
Respected sir,

python auto_martini.py --smi "N1=C(N)NN=C1N" --mol gua --verbose
The sanitize.log file says


[11:10:43] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5

WARNING:__main__:Bad smiles format Nc1ncnn1 found
[11:10:43] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5

WARNING:__main__:Fixed smiles format to Nc1nnc[nH]1
WARNING:__main__:Error with BeautifulSoup constructor

sincerely,
Sneha

**Comment by Snehadixit1994** [comment]
Respected sir,

python auto_martini.py --smi "1nc(nc1N)N" --mol gua --verbose

The sanitize.log file says

[11:20:22] SMILES Parse Error: syntax error for input: '1nc(nc1N)N'
Traceback (most recent call last):
  File "auto_martini.py", line 1309, in <module>
    mol = gen_molecule_smi(args.smi)
  File "auto_martini.py", line 108, in gen_molecule_smi
    cp = Chem.Mol(molecule)
Boost.Python.ArgumentError: Python argument types in
    Mol.__init__(Mol, NoneType)
did not match C++ signature:
    __init__(_object*, RDKit::ROMol, bool, int)
    __init__(_object*, RDKit::ROMol, bool)
    __init__(_object*, RDKit::ROMol)
    __init__(_object*, std::string)
    __init__(_object*)

Sincerely,
Sneha

**Comment by tbereau** [comment]
Dear Sneha,

I don't think this is a valide smiles string. Try with "CCCC" instead.

Best,
Tristan

**Comment by Snehadixit1994** [comment]
Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5

WARNING:__main__:Bad smiles format Nc1ncnn1 found
[01:52:50] Can't kekulize mol.  Unkekulized atoms: 1 2 3 4 5

WARNING:__main__:Fixed smiles format to Nc1nnc[nH]1
WARNING:__main__:Error with BeautifulSoup constructor

**Comment by tbereau** [comment]
Still using the problematic smiles, right? Looks like you're getting a
similar output.

**Comment by anukratig** [comment]
Hi
I run the following command:
python auto-martini --smi "CCCC" --mol NBUT
I am getting the following error-

ALOGPS can't predict fragment: CCCC
Traceback (most recent call last):
  File "auto-martini.py", line 1227, in <module>
    ringAtomsFlat, True)
  File "auto-martini.py", line 858, in printAtoms
    raise Exception("Problem in smi2alogps %s" % smiFrag)
Exception: Problem in smi2alogps CCCC
python2.7: /usr/include/boost/thread/pthread/mutex.hpp:111: boost::mutex::~mutex(): Assertion `!res' failed.
Aborted (core dumped)
-----------------------------------------------------------------------------------------------------------------------------

I added print(soup) and imported lxml as suggested but still getting same error. Please suggest me.
Thanks in advance

**Comment by tbereau** [comment]
Hi anuktratig,

Try running this python code:
```python
from bs4 import BeautifulSoup
import lxml
import requests
session = requests.session()
req = session.get('http://vcclab.org/web/alogps/calc?SMILES=CCCC')
doc = BeautifulSoup(req.content, "lxml")
soup = doc.prettify()
print soup
```

You should be getting this:
```html
<html>
 <body>
  mol_N logP logS SMILES
  <br/>
  mol_1 2.81 -1.91 CCCC
  <br/>
 </body>
</html>
```

Is that the case?

Best,
Tristan

**Comment by anukratig** [comment]
Dear Tristan

I run the pyhton code as suggested. This is what I am getting.
![screenshot from 2017-12-01 16-12-01](https://user-images.githubusercontent.com/34023456/33479337-b683fea4-d6b2-11e7-89e9-dc916f29a4be.png)

**Comment by tbereau** [comment]
Does running the code in the browser yield the same?

**Comment by tbereau** [comment]
Sorry, I meant running the URL.

**Comment by anukratig** [comment]
Yeah it is working on the browser

Thanks

**Comment by tbereau** [comment]
What about from the command line using `wget`?

**Comment by anukratig** [comment]
All packages are working fine.
When i am running the command, it is showing invalid syntax.
I am running the following command
auto-martini --smi "CCCC"  --mol BUT
![image](https://user-images.githubusercontent.com/34023456/37654708-16607e7c-2c69-11e8-875f-1dd4389ca520.png)
![screenshot from 2018-03-20 18-02-20](https://user-images.githubusercontent.com/34023456/37654741-3326032e-2c69-11e8-8fb3-d81bdb0a38ce.png)

**Comment by tbereau** [comment]
Looks like you're running this from a Python terminal. Run auto-martini from the command line instead.

**Comment by anukratig** [comment]
Now this error is showing
![image](https://user-images.githubusercontent.com/34023456/37657057-e7204e92-2c6f-11e8-914d-ffa7d09d1092.png)

**Comment by tbereau** [comment]
I can't reproduce your error. What branch/commit are you on? Also, did you rename the name of the script? That looks different.

**Comment by david-martini** [comment]
Hi
change auto-martini to auto_martini.
